version: '3'
services:
  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - 'elasticsearch'
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - 'discovery.type=single-node'
    expose:
      - '9200'
    ports:
      - '9200:9200'
    restart: always

  kibana:
    image: kibana:7.2.0
    container_name: kibana
    links:
      - 'elasticsearch'
    ports:
      - '5601:5601'
    restart: always
